### ISSUE TITLE
centos title error

### ISSUE THREAD

**Issue by yzzshmily** [JLULUG/issues#11]
<img width="669" alt="image" src="https://github.com/JLULUG/mirrors-web/assets/5506825/81d2cc2d-e105-4aa9-8183-7293e51a66b9">
企业级

**Comment by RtYkk** [comment]
by design.

**Comment by TechCiel** [comment]
这是预期行为。RHEL 之所以能被称为企业级，是因为有随时待命的支持团队服务客户，CentOS 作为社区的换壳版，其可靠性水平与其他发行版相若，遇到问题还是得管理员自己起夜来修。
