### ISSUE TITLE
pypi 迟迟没更新成功

### ISSUE THREAD

**Issue by diaowinner** [JLULUG/issues#12]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/JLULUG/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

pypi 一直显示「在 X 分钟后」更新但没成功。最后一次同步在 31 天前。  
这导致了我在配置编程环境时候即使适配了新的 pixel_font_builder（pypi 当中的一个库）并重置了虚拟环境也无法使我的项目编译成功：[这里](https://github.com/TakWolf/pixel-font-builder/issues/6#issuecomment-2152267533)。

### 期望的现象 / What you expected

pypi 正常更新。

### 如何重现此问题 / How to reproduce

点开网站就看到了：  
![](https://github.com/JLULUG/issues/assets/32033700/de8a5c27-e173-42a1-a9b5-e890bf7cfc4b)

### 操作系统版本 / OS version

Arch Linux，更新于 2024 年 6 月 6 日

### 浏览器或客户端版本 / Browser/client version

Firefox Developer Edition, 127.0b9

### 其他环境 / Other environments

Python 及其虚拟环境已经在当天重置。本人采用另一个镜像源才成功更新 pypi 包。

### 其他 / Anything else

我本身在 Python 这方面经验不是太多，如有错误不吝赐教。

**Comment by TechCiel** [comment]
您好，经过检查发现 PyPI 最近体积增加较快，用于同步的独立存储阵列已满导致同步失败，非常抱歉影响到您的业务使用。

目前我们正在将 PyPI 存储库迁移到主阵列，这可能需要数天时间。

在迁移完成并重新同步之前，我们暂时将该项目重定向到邻近的其他高校镜像源。

**Comment by TechCiel** [comment]
迁移和重新同步已完成，服务已恢复。

**Comment by Dagsi** [comment]
@TechCiel 这个问题又出现了

**Comment by TechCiel** [comment]
@Dagsi 感谢您的报告。经查，系日前[系统维护](http://mirrors.jlu.edu.cn/_news/#2024-12-22-maint)后，同步工具依赖环境损坏导致，现已修复，正在恢复同步。
