### ISSUE TITLE
申请KeyarchOS软件仓库和ISO镜像

### ISSUE THREAD

**Issue by e-wanerer** [JLULUG/issues#13]
### 先决条件 / Prerequisites

- [X] 【重要！】我已仔细阅读过[请求新镜像须知](https://github.com/JLULUG/issues/issues/10)
I've carefully read the [Notes on Mirror Requests](https://github.com/JLULUG/issues/issues/10).

- [X] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/JLULUG/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 申请人身份 / Identity

项目维护者 / Project Maintainer

### 项目简介 / Introduction

**KeyarchOS操作系统简介**：KeyarchOS是浪潮信息基于Linux Kernel、OpenAnolis等开源技术自主研发的一款服务器操作系统，支持x86、ARM等主流架构处理器，具备成熟的 CentOS 迁移和替换能力，可满足云计算、大数据、分布式存储、人工智能、边缘计算等应用场景需求。
**申请添加KeyarchOS原因**：当前CentOS已经全面停止更新，国产操作系统迁移已经迫在眉睫，在高校使用方面，KeyarchOS已经多所高校进行了项目落地，包括上海交通大学、武汉科技大学、厦门大学等，后续会有更多的高校项目，为了方便校内人员使用，因此申请增加KeyarchOS镜像源。

### 上游地址与镜像方法 / Upstream & Method

**同步方式** ：rsync
**rsync地址**：kos.ieisystem.com::keyarchos   ，同步方法如：rsync -avz --progress --delete root@kos.ieisystem.com::keyarchos   /data
  **密码**   ：Keyarchos_yum

### 镜像大小 / Size

250G

**Comment by TechCiel** [comment]
> 为了方便校内人员使用

@e-wanerer 是否能够提供来自吉林大学网络*的访问统计数据，或与吉林大学校内单位的合作信息？

*: 地址段信息见 https://mirrors.jlu.edu.cn/_static/cidr.txt

**Comment by e-wanerer** [comment]
> @e-wanerer 是否能够提供来自吉林大学网络*的访问统计数据，或与吉林大学校内单位的合作信息？
> 
> *: 地址段信息见 https://mirrors.jlu.edu.cn/_static/cidr.txt
@TechCiel 您好，校内合作信息：
 吉林大学理论化学研究所，高性能集群环境，需要在KeyarchOS操作系统上进行开发测试。

**Comment by TechCiel** [comment]
您好，经综合考虑，我们决定暂不镜像 KeyarchOS 项目，原因如下：

- 该项目发布仅约一年，知名度较低，用户量较少，未见活跃开放社区，也未见上游贡献
- 该项目作为企业主导的订阅制商业版操作系统，不符合教育网镜像站公益性的宗旨和要求
- CentOS 退役前后国内外大量出现替代品，本站已镜像使用较为广泛的 Rocky Linux (#9) ，以满足校内多个单位需求
- 该系统如作为商业解决方案的一部分销售，企业应自行配套相关软件分发基础设施
- 该项目未见任何其他镜像站镜像

感谢您对镜像站的支持和关注，愿您与自由软件度过愉快的时光。
