### ISSUE TITLE
[镜像请求] GXDE OS 镜像请求

### ISSUE THREAD

**Issue by shenmo7192** [JLULUG/issues#14]
### 先决条件 / Prerequisites

- [X] 【重要！】我已仔细阅读过[请求新镜像须知](https://github.com/JLULUG/issues/issues/10)
I've carefully read the [Notes on Mirror Requests](https://github.com/JLULUG/issues/issues/10).

- [x] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/JLULUG/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 申请人身份 / Identity

项目维护者 / Project Maintainer

### 项目简介 / Introduction

GXDE OS是以 GXDE 为特色，基于 Debian 12 Bookworm 构建的桌面发行版，集成顶栏，全局菜单，星火应用商店，AmberCE 兼容环境，幻梦动态壁纸等多个社区开源项目，支持如意玲珑软件包格式，从 deepin 15 起步，重启和 backports 了十余款桌面组件和整个桌面环境，支持国产信创机型使用

GXDE 桌面环境源自 deepin 15 时代的重生，不仅带回了经典体验，还引入了多种多样的扩展组件、体验优化和问题修复。它兼具经典与创新，确保了更流畅且更丰富的用户体验。
![图片](https://github.com/user-attachments/assets/103fa469-18d0-4408-9998-2cd763f7abbf)

### 上游地址与镜像方法 / Upstream & Method

apt: https://repo.gxde.org/gxde-os/

rsync: port=40222 rsync://gxde-rsync@frp-cup.top/repo

rsync使用白名单方式访问

### 镜像大小 / Size

约15-20G，短期内不会大幅增加

### 备注 / Notes

官网: https://www.gxde.org

开源地址: https://gitee.com/GXDE-OS/

仓库中只包含开源软件和构建出的ISO文件

**Comment by TechCiel** [comment]
@shenmo7192 您好，经综合考虑，由于下列原因，我们决定暂不镜像 GXDE OS 项目。

- 用户规模较小，且未见明显校内或地区性使用需求
- 从仓库情况来看，项目历史不到一年，主要贡献者仅 2 人，主页刚刚创建不到两个月
- 使用内网穿透服务搭建的官方仓库，受制于流量带宽限制和网络波动，恐难以满足稳定同步的要求
- 未见其他镜像站镜像该项目

本站的收录原则一向对于本土社群自主创立的项目有所倾斜，但仍需考量项目的实际发展和建立镜像的现实需要，欢迎您在项目进一步发展成熟后再行申请镜像，感谢您对镜像站的支持和关注。

**Comment by shenmo7192** [comment]
> @shenmo7192 您好，经综合考虑，由于下列原因，我们决定暂不镜像 GXDE OS 项目。
> 
>     * 用户规模较小，且未见明显校内或地区性使用需求
> 
>     * 从仓库情况来看，项目历史不到一年，主要贡献者仅 2 人，主页刚刚创建不到两个月
> 
>     * 使用内网穿透服务搭建的官方仓库，受制于流量带宽限制和网络波动，恐难以满足稳定同步的要求
> 
>     * 未见其他镜像站镜像该项目
> 
> 
> 本站的收录原则一向对于本土社群自主创立的项目有所倾斜，但仍需考量项目的实际发展和建立镜像的现实需要，欢迎您在项目进一步发展成熟后再行申请镜像，感谢您对镜像站的支持和关注。

好的，我们会在项目更加成熟后再申请
