### ISSUE TITLE
[镜像请求] openKylin（开放麒麟）申请加入镜像站

### ISSUE THREAD

**Issue by fenshezhuiyi** [JLULUG/issues#5]
### 先决条件 / Prerequisites

- [x] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/JLULUG/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 项目简介 / Introduction

openKylin 社区是在开源、自愿、平等和协作的基础上，由基础软硬件企业、非营利性组织、社团组织、高等院校、科研机构和个人开发者共同创立的一个开源社区，致力于通过开源、开放的社区合作，构建桌面操作系统开源社区，推动Linux开源技术及其软硬件生态繁荣发展。 ​
官网地址：https://www.openkylin.top/

### 上游地址与镜像方法 / Upstream & Method

配置与同步命令详情：https://www.openkylin.top/public/pdf/mirror_application.pdf

**Comment by TechCiel** [comment]
该申请存在以下问题，请予补正：

- 该文件中官方仓库地址，文本与超链接指向不同，请确认申请的是 ubuntukylin 还是 openkylin 项目
- 提供的 rsync 同步仓库系统报告大小远超申请载明大小，请重新确认镜像大小
- 请注意，你提供的公开 PDF 文件中包含同步密码，我协会不对此密码被滥用造成的后果负责

**Comment by fenshezhuiyi** [comment]
收到，感谢站长的回复：
1、openKylin，文档请重新刷新进入https://www.openkylin.top/public/pdf/mirror_application.pdf
2、已更新在文档
3、这个是开放的，没有关系
谢谢~

**Comment by fenshezhuiyi** [comment]
站长，您好，该申请已过去1个月，可否帮忙看看，谢谢

**Comment by TechCiel** [comment]
您好，经运维综合考虑，由于以下原因，我们决定不将 OpenKylin 项目列入镜像计划。

- 该项目发布尚不足一年，目前用户数量少，影响力一般，未见有突出创新特性，未来也看不到前景，不符合支持主流项目的条件
- 该项目显然是由企业主导而不是社区主导的，且大部分以麒麟系关联企业为主，不符合支持社区新创项目的条件
    - 对于企业发行版（如 RHEL），一般建议相关企业自行负担仓库网络带宽
- 修正后的项目大小仍然不准确，实际项目大小远超申报，该尺寸的项目也不符合支持小微项目的条件
- 该项目官方仓库设置在中国大陆境内，连接性良好，经测试带宽也较充足，下载不存在明显困难

除以上事实性条件之外，我们还注意到 OpenKylin 刚刚成立即产生了大量媒体报道、政府合作、活动、会议等材料，唯活动范围仅限大陆境内，且文稿通稿痕迹严重，缺少实质性工作，同时在国际上的影响力几乎为零，未见任何讨论也未见对上游贡献，甚至没有优麒麟受到的关注高，我们难以理解，这样的「国内项目」究竟希望在开源世界中扮演怎样的角色。

此外，OpenKylin 在大量中文新闻中被称为"根社区"，这是一个没有明确定义也不常提起的概念，但不与上游挂钩更新并不能称为一个独立开发的发行版，该称呼的大量出现有自我炒作嫌疑。更何况，该项目软件仓库中很多软件都是基于 Debian 的软件包，然后进行小改甚至未改的产物，实际自主研发比例不高，若说是衍生版尚且不知是否合格，更遑论独立开发。

综合这些原因，我们不得不怀疑，OpenKylin 究竟是一个技术性项目，还是一个宣传为主的套壳甚至空壳的政绩工程。在该等疑虑充分消除前，我们不会考虑镜像 OpenKylin 项目。
