### ISSUE TITLE
[镜像请求] 请求添加 ImmortalWrt 镜像

### ISSUE THREAD

**Issue by douglarek** [JLULUG/issues#8]
### 先决条件 / Prerequisites

- [X] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/JLULUG/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 项目简介 / Introduction

ImmortalWrt 是 OpenWrt 的一个第三方分支，主要针对国人用户开发，提供更多的本地化软件包和设备支持。

项目地址： https://github.com/immortalwrt

### 上游地址与镜像方法 / Upstream & Method

下载地址： https://downloads.immortalwrt.org/

镜像方法：

```
env RSYNC_PASSWORD="immortalwrt-org" rsync -4ahv --delete-delay "rsync://firmwarepublic@rsync-mirror.infra.immortalwrt.org/firmware-public/" "immortalwrt/"
```

### 镜像大小 / Size

~930 GB

**Comment by 1715173329** [comment]
@TechCiel 您好，目前我是 ImmortalWrt 项目的维护者。

> 由于空间比较紧张，该项目尺寸较大，是否可能有部分镜像的方案？

目前 18.06/18.06-k5.4 分支已经停止维护，您可以排除这部分，大约占用 200 GB。
如果仍然受限，也可以进一步排除 snapshots 的镜像，大约在 165 GB 左右。

> 该项目中包含的软件，尤其是嵌入式驱动程序等，是否均适用自由或开源软件许可证，并允许公开再分发？

- 目前集成的所有内核驱动程序均适用 GPL-2.0 许可证。允许再分发

> 是否能提供吉林大学网络访问官方源的日志统计信息？

我们目前未设计这部分，也不太愿意收集与 IP 有关的统计信息。

> 是否能说说为什么要独立于上游 OpenWRT 进行开发，而不是直接贡献上游，或者做一个额外软件源？

我们的开发并不“独立”于上游，但我目前只拥有 packages 仓库的 push 权限，在其他仓库的 PR 审核时间几乎会无限延长，开发者们通常只关注自己感兴趣的那部分，一个 PR 甚至可以拖一两年。
以及 OpenWrt 要求大部分更改必须提交到原项目并且被接受（虽然说是灵活底线），使得这一流程更加漫长。

我们对原有代码的修改很多，从内核到软件包再到 LuCI。
有些属于 hack，有些是原厂 GPL 驱动，有些不符合上游代码要求标准，还有些只是因为单纯的大小问题上游不愿意改。
这部分三言两语难说清楚，要讨论的话可以通过 TG 联系我： https://t.me/Kasugano_Sora

感谢您的回复。

**Comment by TechCiel** [comment]
@1715173329 感谢回复。

我按照不同步快照和 18.06 加了 `--exclude '/snapshots/' --exclude '/releases/*18.06*'` 统计了一下：

```
Number of files: 2,071,725 (reg: 2,066,579, dir: 5,134, link: 12)
Total file size: 559.00G bytes
File list size: 108.39M
```

有几个进一步的问题：

- 同步这部分内容对项目而言是否有意义，是否大部分用户都只使用这部分资源？
- 我们注意到文件数量比较多，文件比较细碎，能否大致说明下原因？
- 基于大量小文件带来的 IO 负担，我们可能只能在低峰期每日进行同步，是否可行？
- 我们注意到官方源在海外，项目申请国内各高校镜像的主要原因是因为带宽成本和连接性吗？
- 能否提供官方源总请求量的统计数据？
- 你们对项目大小的增长有何预期？

按照目前的情况来看，我们可能在下一批次计划镜像结束后，考虑以「实验性项目」的方式加入 ImmortalWRT 。

**Comment by 1715173329** [comment]
> 同步这部分内容对项目而言是否有意义，是否大部分用户都只使用这部分资源？

是的，这部分属于我们正在维护的稳定版本，也是我们推荐用户使用的版本。

> 我们注意到文件数量比较多，文件比较细碎，能否大致说明下原因？

应该与其他 Linux 发行版类似，OpenWrt 将每个软件包打包为单独的 IPK 文件，目前每个目标拥有大约 1,000 个软件包，每个架构大约有 9,000 个软件包，整合起来小文件会非常多。

> 基于大量小文件带来的 IO 负担，我们可能只能在低峰期每日进行同步，是否可行？

没问题。

> 我们注意到官方源在海外，项目申请国内各高校镜像的主要原因是因为带宽成本和连接性吗？

是的，目前我们无法负担高昂的国内带宽费用。

> 能否提供官方源总请求量的统计数据？

目前主站每天请求数量大约为 108,000+ 次；天翼云镜像站目前由群友托管，暂无相关数据。

> 你们对项目大小的增长有何预期？

https://openwrt.org/downloads#how_to_mirror
按 OpenWrt 计划，预计每年增加 300 GB 空间占用（每年发布一个新 release 版本）。

**Comment by TechCiel** [comment]
好的，我们将在近期尝试进行初始同步，该 issue 将保持 open 。镜像上线后，将通过该 issue 通知。

**Comment by 1715173329** [comment]
感谢您的支持！

**Comment by TechCiel** [comment]
初始同步已完成，该镜像已经投入实验性运行。

排除参数为：`--exclude /snapshots/ --exclude /releases/*18.06* --exclude /releases/*-SNAPSHOT`

目前工作大小为 577 GiB 。

**Comment by TechCiel** [comment]
@1715173329 请留意，官方仓库的同步服务已经至少一天处于不可用状态。

**Comment by 1715173329** [comment]
> @1715173329 请留意，官方仓库的同步服务已经至少一天处于不可用状态。

目前我们正在迁移文件服务器，预计于今日稍晚完成。感谢您的通知。

**Comment by 1715173329** [comment]
更新：目前已经迁移完成，rsync 服务已恢复。
