### ISSUE TITLE
[镜像请求] Rocky Linux

### ISSUE THREAD

**Issue by kingstdio** [JLULUG/issues#9]
### 先决条件 / Prerequisites

- [X] 该项目未在其他被标为 wontfix 的 [issues](https://github.com/JLULUG/issues) 中讨论过。
No previous issues with "wontfix" label have discussed about mirroring this project.

### 项目简介 / Introduction

JLU智慧学工集群，校内生产环境从CentOS 7 迁移到了Rocky Linux 8， 能否在校内帮忙添加一份Rocky Linux 的源。

### 上游地址与镜像方法 / Upstream & Method

https://github.com/rocky-linux/rocky-tools
可以参考mirror.nju.edu.cn
https://mirror.nju.edu.cn/

### 镜像大小 / Size

1.02T

**Comment by TechCiel** [comment]
@kingstdio 您好，感谢您对镜像站的关注。

CentOS 的终止产生了 CentOS Stream、Rocky Linux、AlmaLinux 等多个发行版，先期有了解过情况，但基本都存在用户基数小、占用空间高、彼此重复度高等问题，有鉴于镜像站有限的资源，我们仍需进一步观察并审慎决定镜像选择。

从技术人员的个人角度讲，在可能的情况下，我更建议相关系统换用Debian 等成熟稳定的发行版，但我也理解有些旧系统迁移困难。

我们会将校内单位的需要列入主要考量，在做出最终决定前将保持该 issue 开启，如有进一步消息也将通过该 issue 通知。

**Comment by TechCiel** [comment]
考虑到 Rocky Linux 近期在 CentOS 替代发行版中发展势头较好，也基于多个单位的业务需要，我们决定增加 Rocky Linux 镜像，目前正在初始同步中。

感谢您对镜像站和网络中心工作的支持和关注。

**Comment by TechCiel** [comment]
已完成同步并进入官方镜像列表。
